# Generated by Django 4.1.4 on 2023-01-11 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_schedule_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='author',
            new_name='user',
        ),
    ]
